import { test, expect } from '@playwright/test'
test('ajustes: secciones exclusivas, profundidad del catálogo y navegación móvil', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/tests/ajustes-ui.html')
  await expect(page.getByRole('heading', { name: 'General', exact: true })).toBeVisible()
  await expect(page.getByText('EXPLORAR POR CATEGORÍA')).toHaveCount(0)
  await page.screenshot({ path: 'node_modules/.cache/ajustes-desktop.png', fullPage: true })
  await page.getByRole('link', { name: 'Mis módulos', exact: true }).click()
  await expect(page.getByText('EXPLORAR POR CATEGORÍA')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'General', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Punto de venta/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Mesas/ })).toHaveCount(0)
  await page.getByRole('link', { name: 'Ventas en el local', exact: true }).click()
  await expect(page.getByRole('button', { name: /^Mesas/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Gestión de stock/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Facturación ARCA/ })).toHaveCount(0)
  await page.getByRole('button', { name: /Punto de venta/ }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: 'Facturación', exact: true }).click()
  await page.getByRole('button', { name: /Facturación ARCA/ }).click()
  await expect(page.getByRole('dialog').getByRole('button', { name: /Activar/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: 'Tu tienda online', exact: true }).click()
  await expect(page.getByRole('button', { name: /Avisos automáticos/ })).toBeVisible()
  await page.getByRole('link', { name: 'Cómo cobrás', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Módulos de esta sección' }).getByRole('button', { name: /Mercado Pago/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Avisos automáticos/ })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Pagos', exact: true })).toBeVisible()
  await page.screenshot({ path: 'node_modules/.cache/ajustes-cobros.png', fullPage: true })
  await page.getByRole('link', { name: 'Suscripción y pagos', exact: true }).click()
  await expect(page.getByText('Comprobantes e historial de pagos')).toBeVisible()
  await expect(page.getByText('EXPLORAR POR CATEGORÍA')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByLabel('Ir a sección').selectOption('general')
  await expect(page.getByRole('heading', { name: 'General', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'node_modules/.cache/ajustes-mobile.png', fullPage: true })
  expect(errors).toEqual([])
})
