import { test, expect } from '@playwright/test'

test('buscador compacto, teclado, cambio de columna y borrador persistente', async ({ page }) => {
    await page.goto('/tests/pos-catalogo-ui.html')
    const search = page.getByPlaceholder('Buscar producto o tag...')
    const producto = page.getByRole('button', { name: /Empanada de carne/ })
    await expect(search).toBeVisible()
    await expect(producto).toHaveCount(0)
    await search.fill('empa')
    await expect(producto).toBeVisible()
    await search.press('Enter')
    await expect(page.getByRole('status')).toHaveText('1 ítems')
    await expect(search).toHaveValue('')
    await expect(search).toBeFocused()
    await expect(producto).toHaveCount(0)

    await page.getByRole('button', { name: 'Configurar POS', exact: true }).click()
    await page.getByRole('switch', { name: 'Catálogo en tercera columna' }).click()
    await page.getByRole('button', { name: 'Guardar', exact: true }).click()
    await expect(page.getByRole('complementary', { name: 'Catálogo' }).getByPlaceholder('Buscar producto o tag...')).toBeVisible()
    await expect(producto).toBeVisible()
    await expect(page.getByRole('status')).toHaveText('1 ítems')

    await page.getByRole('button', { name: 'Configurar POS', exact: true }).click()
    await page.getByRole('switch', { name: 'Catálogo en tercera columna' }).click()
    await page.getByRole('button', { name: 'Guardar', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Comanda' }).getByPlaceholder('Buscar producto o tag...')).toBeVisible()
    await expect(producto).toHaveCount(0)
    await page.getByRole('button', { name: 'Cambiar vista', exact: true }).click()
    await expect(search).toHaveCount(0)
    await page.getByRole('button', { name: 'Cambiar vista', exact: true }).click()
    await expect(search).toBeVisible()
    await expect(page.getByRole('status')).toHaveText('1 ítems')
    await page.reload()
    await expect(search).toBeVisible()
    await expect(producto).toHaveCount(0)
    await expect(page.getByRole('status')).toHaveText('1 ítems')
})
