//! Build script del plugin.
//!
//! `tauri_plugin::Builder` hace tres cosas, todas necesarias y ninguna evidente:
//!
//! 1. Genera los permisos ACL de los comandos (`permissions/autogenerated/`).
//! 2. Con `android_path("android")` copia las fuentes de `tauri-android` a `android/.tauri/` y
//!    **emite `cargo:android_library_path=<...>/android`**. Ese es el mecanismo por el que el build
//!    script de la app (`tauri-build::mobile::generate_gradle_files`) agrega el módulo Gradle del
//!    plugin a `gen/android/tauri.settings.gradle` y a `app/tauri.build.gradle.kts`: sin esto, las
//!    clases Kotlin no entran al APK y el plugin no existe en tiempo de ejecución.
//! 3. Define los alias de cfg `mobile` / `desktop` del crate.
//!
//! Los nombres de los comandos son los de los métodos Kotlin anotados con `@Command`: se indexan
//! por nombre de método (reflexión), así que un typo acá no compila de menos, falla en runtime.

const COMMANDS: &[&str] = &["getPrinters", "sendPrintJob"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
